name: Build && Deploy
on:
  push:
    branches:
      - entranceMicroservice
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse HEAD revision
        run: echo "COMMIT_HASH=$(git rev-parse HEAD | head -c 8)" >> "$GITHUB_ENV"

      - name: Build mh_entrancemicroservice
        run: docker build -f Dockerfile -t "mh_entrancemicroservice:$COMMIT_HASH" .
      - name: Tag mh_entrancemicroservice
        run: >
          docker image tag "mh_entrancemicroservice:$COMMIT_HASH"
          "ghcr.io/meow-hacks/mh_entrancemicroservice:latest"

      - name: Login into registry
        run: docker login -u meow-hacks -p ${{ secrets.MEOWHACKS_ACCESS_TOKEN_CLASSIC }} ghcr.io

      - name: Push mh_entrancemicroservice image
        run: docker push ghcr.io/meow-hacks/mh_entrancemicroservice:latest

      - name: Delete old mh_entrancemicroservice images
        uses: actions/delete-package-versions@v5
        with:
          package-name: mh_entrancemicroservice
          package-type: container
          min-versions-to-keep: 1
          token: ${{ secrets.MEOWHACKS_ACCESS_TOKEN_CLASSIC }}

      - name: Deploy containers
        run: |
          echo "${{ secrets.DEPLOY_CERT }}" > deploy.cert
          chmod 600 deploy.cert
          ssh -o "StrictHostKeyChecking no" -i deploy.cert "ci@${{ vars.DEPLOY_HOST }}" "cd ~/mh_entrancemicroservice && ./deploy.sh"