name: Sync static.yml across branches

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/static.yml

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Забираем все ветки для доступа

      - name: Sync static.yml with target branches
        run: |
          branches=("UsersMicroservice" "LoginMicroservice" "adminMicroservice")
          for branch in "${branches[@]}"; do
            echo "Switching to branch: $branch"
            git checkout $branch

            # Копируем файл из ветки main
            git checkout main -- .github/workflows/static.yml

            # Проверяем изменения и коммитим, если необходимо
            if git diff --quiet; then
              echo "No changes to commit for branch $branch."
            else
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git add .github/workflows/static.yml
              git commit -m "Sync static.yml from main"
              git push origin $branch
              echo "Updated static.yml in branch $branch."
            fi
          done
